ams_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    # JET page
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # Admin Page
    url(r'^dashboard/', include(admin.site.urls)),
    # Login and logout URLs
    url(r"^accounts/", include("registration.backends.hmac.urls")),
    # Attendance URLs
    url(r"^attendance/", include("main.urls")),
    # Dashboard URLs
    # url(r"^dashboard/", include("dashboard.urls")),
    # Redirecting / to /attendance/
    url(r"^$", RedirectView.as_view(url="/attendance/")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    # /attendance/ (Access: Professors)
    # Initial page: This is where you select your class and subject.
    url(r"^$", views.InitialView.as_view(), name="initial"),
    # /attendance/entry/ (Access: Professors)
    # Attendance page: This is where you mark your attendance.
    url(r"^entry/", views.AttendanceView.as_view(), name="attendance"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import signals
from django.db.models.signals import post_save, pre_delete
from .middleware import RequestMiddleware

# Create your models here.


class UserType(models.Model):
    """
        UserType: Used to store the type of user Ex: Student, Principal, Professor etc.
    """

    name = models.CharField("Type of User", max_length=50)

    def __str__(self):
        return self.name


class User(AbstractUser):
    """
        User: Used for storing user details
    """

    phone = models.CharField("Phone", max_length=15, null=True, blank=True)
    subjects = models.ManyToManyField("subject", blank=True)
    email = models.EmailField("Email", max_length=250, null=True, blank=True)
    sem = models.CharField("Semester", null=True, blank=True, max_length=50)
    sec = models.CharField("Section", max_length=10, null=True, blank=True)
    department = models.ForeignKey("department", null=True, blank=True)
    user_type = models.ManyToManyField("UserType")
    father = models.CharField("Father's Name", max_length=50, null=True, blank=True)
    mother = models.CharField("Mother's Name", max_length=50, null=True, blank=True)
    phone_parent = models.CharField(
        "Parent's Phone Number", max_length=50, null=True, blank=True
    )


class Subject(models.Model):
    """
        Subject: Holds details about each subject
    """

    name = models.CharField("Subject Name", max_length=50)
    code = models.CharField("Subject Code", max_length=50)

    theory = models.BooleanField(default=True)
    elective = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name + "->" + self.code)


class Teaches(models.Model):
    """
        Teaches: Holds details about the subject that the teacher teaches.
        It links the Subject and the Teacher with the sem, sec and department that they are teaching.
        We are storing sem, sec, deaprtment of the student to get the name of the teacher by matching the
        details with the user table.
    """

    teacher = models.ForeignKey("user")
    subject = models.ForeignKey("subject")

    sem = models.CharField("Student's Semester", max_length=50)
    sec = models.CharField("Student's Section", max_length=50)
    department = models.ForeignKey("department", null=True)

    # 	batch = models.CharField("Student's Batch", max_length=50, null=True, blank=True)
    # 	sub_batch = models.CharField("Student's sub batch", max_length=50, null=True, blank=True)
    # 	ug = models.BooleanField(default=False)

    count = models.IntegerField("Student Count", default=0, null=True, blank=True)

    def __str__(self):
        return (
            self.department.name
            + " -> "
            + self.subject.name
            + " -> "
            + self.sem
            + " "
            + self.sec
        )


class Department(models.Model):
    """
        Department
    """

    name = models.CharField("Department Name", max_length=50)

    def __str__(self):
        return self.name


class Attendance(models.Model):
    """
        Attendance: It stores class details even if no one is absent. 
        It acts as a proof that, that particular class was there.
    """

    date_time = models.DateTimeField(auto_now=True, auto_now_add=False)
    teaches = models.ForeignKey("teaches", null=True)

    def __str__(self):
        return f"{self.teaches.teacher.first_name} -> {self.date_time}"


class Absentees(models.Model):
    """
        Absentees: Stores the absentees
    """

    user = models.ForeignKey("user")
    attendance = models.ForeignKey("attendance")

    def __str__(self):
        return self.user.first_name


class ChangeStatus(models.Model):
    """
        Stores the details of when the attendance is changed, by whom and to what
    """

    user = models.ForeignKey("user")
    datetime = models.DateTimeField(auto_now_add=True)
    attendance = models.ForeignKey("attendance")
    detail = models.TextField()

    def __str__(self):
        return self.detail

    class Meta:
        verbose_name_plural = "Logs"


def create_status(sender, instance, created=None, **kwargs):
    request = RequestMiddleware(get_response=None)
    request = request.thread_local.current_request
    if request.user.is_superuser:
        if created:
            detail = f"Admin marked {instance.user.first_name} absentee for class {instance.attendance.teaches.subject}"
        else:
            detail = f"Admin marked {instance.user.first_name} present for class {instance.attendance.teaches.subject}"
        ChangeStatus.objects.create(
            user=request.user, attendance=instance.attendance, detail=detail
        )


post_save.connect(create_status, sender=Absentees)
pre_delete.connect(create_status, sender=Absentees)

templates/attendance.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<nav style="width:100%;" class="navbar navbar-expand-md navbar-dark">
	<a class="navbar-brand" href="#">AMS</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="collapsibleNavbar">
		<ul class="navbar-nav ml-auto">
			<li>
			</li>
			<li class="nav-item">
				<a href="{% url 'auth_logout' %}" class="nav-link">
					Logout
				</a>
			</li>
		</ul>
	</div>
</nav>
<div class="float-right p-2">
	<label class="switch navbar-nav">
		<input id="cmn-toggle-4" type="checkbox">
		<span class="slider round"></span>
	</label>
</div>
<div style="margin-top:3%;" class="container">
	<div id="details_pc" class="row">
		<div class="col">
			<p>Teacher: {{ teaches.teacher.first_name }}</p>
		</div>
		<div class="col">
			<p>Class: {{ teaches.sem }} {{ teaches.sec }}</p>
		</div>
		<div class="col">
			<p>Date: <span class="date"></span></p>
		</div>
		<div class="col">
			<p>Hour: <span class="time"></span></p>
		</div>
	</div>
	<div id="details_mob" class="d-none">
		<div class="row">
			<div class="col">
				<p>Teacher:{{ teaches.teacher.first_name }}</p>
			</div>
			<div class="col">
				<p>Class: {{ teaches.sem }} {{ teaches.sec }}</p>
			</div>
			<div class="col">
				<p>Date: <span class="date"></span></p>
			</div>
			<div class="col">
				<p>Hour: <span class="time"></span></p>
			</div>
		</div>
	</div>
	<div class="table100 ver3 m-b-110">
		<div class="table100-head">
			<table class="table table-gray fixed-header">
				<thead>
					<tr class="text-center">
						<th style="width:20%;">Sr. No.</th>
						<th style="width:50%;">Name</th>
						<th style="width:30%;">Absent <span id="hide" style="font-size:0.8em;">(mark if absent)</span>
						<input id="main_radio" type="checkbox" onClick="toggle(this)">
					</th>
				</tr>
			</thead>
		</table>
	</div>
	<div class="table100-body js-pscroll">
		<table style="width:100%;">
			<tbody>
				{% for i in student_list %}
					<tr class="text-center row100 body trigger">
						<td style="width:20%;">{{ forloop.counter }}</td>
						<td style="width:50%;">{{ i.first_name }}</td>
						<td style="width:30%;"><div style="text-align:center;" class="checkbox"><input type="checkbox" class="orm-check-input" id="check2" name="student" value="{{i.username}}"></div></td>
					</tr>
					{% empty %}
					<tr id="oops">
						<span class="text-danger"> Oops! Something went wrong. Please contact your IT support.</span>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
<input style="margin-bottom:10%;" type="button" class="btn submit-btn float-right mt-4" value="Submit" data-toggle="modal" data-target="#myModal" id="submit">
</div>
<div class="modal" id="myModal">
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h4 class="modal-title">Absentees</h4>
			<button type="button" class="close" data-dismiss="modal">&times;</button>
		</div>
		<div class="modal-body">
			<form id="main_form" style="margin-bottom:15%;" method="POST">{% csrf_token %}
				<div class="table100 ver3 m-b-110">
					<div class="table100-head">
						<table class="table table-gray fixed-header">
							<thead>
								<tr class="text-center">
									<th style="width:20%;">Sr. No.</th>
									<th style="width:50%;">Name</th>
									<th style="width:30%;">Absent <span id="hide" style="font-size:0.8em;">(mark if absent)</span>
								</th>
							</tr>
						</thead>
					</table>
				</div>
				<div class="table100-body js-pscroll">
					<table style="width:100%;margin-top:5%;">
						<tbody class="modal-table">
						</tbody>
					</table>
				</div>
			</div>
			<input type="submit" class="btn submit-btn float-right mt-4" value="Submit">
		</form>
		<span>Total absentee: <span class="count"></span></span>
	</div>
</div>
</div>
</div>
{% endblock %}
{% block script %}

{{ super }}
<script type="text/javascript">
$('.submit-btn').click(function() {
    $('.modal-table').html('');
    var empty = true;
    var count = 0;
    $('.trigger').each(function() {
        i = 0;
        $(this).find('td').each(function() {
            i++;
            if (i == 3) {
                if ($(this).children().children().prop('checked') == true) {
                    empty = false;
                    count++;
                    $(this).children().children().removeClass('trigger');
                    $('.modal-table').append($(this).parent().clone());
                }
            }
        });
    })
    if (empty) {
        $('.modal-table').append("<h3 class='text-info' align='center'>No absentee :-)</h3>");
    }
    $('.count').html(count);
})
$(document).on('show.bs.modal', '#myModal', function (e) {
    $('.modal-body').each(function() {
    	$(this).find('tr').each(function() {
    		$(this).children().children().children().addClass('modal-checkbox')
    	})
    })
    $('.modal-checkbox').each(function() {
    	count = parseInt($('.count').html());
    	$(this).change(function() {
    		if($(this).prop('checked') == false) {
    			$('.count').html(count - 1);
    			count = parseInt($('.count').html())
    			if($('#cmn-toggle-4').prop('checked') == true) {
	  				$(this).parent().parent().removeClass('selected')
					$(this).parent().parent().siblings().removeClass('selected')
	  			}
	  			else {
	  				$(this).parent().parent().removeClass('selected_dark')
					$(this).parent().parent().siblings().removeClass('selected_dark')
	  			}
    		}
    		else {
    			$('.count').html(count + 1);
    			count = parseInt($('.count').html())
    			if($('#cmn-toggle-4').prop('checked') == true) {
	  				$(this).parent().parent().addClass('selected')
					$(this).parent().parent().siblings().addClass('selected')
  				}
  				else {
	  				$(this).parent().parent().addClass('selected_dark')
					$(this).parent().parent().siblings().addClass('selected_dark')
	  			}
    		}
    	})
    })
});
</script>
<script>
if($('#oops').length > 0) {
	$('#submit').attr('disabled', 'true');
	$('#submit').css('cursor', 'not-allowed');
}
</script>
<script>
$(function() {
	$('.orm-check-input').each(function() {
		$(this).change(function() {
			if($(this).prop('checked') == true){
				if($('#cmn-toggle-4').prop('checked') == true) {
	  				$(this).parent().parent().addClass('selected')
					$(this).parent().parent().siblings().addClass('selected')
  				}
  				else {
	  				$(this).parent().parent().addClass('selected_dark')
					$(this).parent().parent().siblings().addClass('selected_dark')
	  			}
			}
			else {
				if($('#cmn-toggle-4').prop('checked') == true) {
	  				$(this).parent().parent().removeClass('selected')
					$(this).parent().parent().siblings().removeClass('selected')
	  			}
	  			else {
	  				$(this).parent().parent().removeClass('selected_dark')
					$(this).parent().parent().siblings().removeClass('selected_dark')
	  			}
			}
		})
	})
})
</script>
<script>
$(function() {
    if (screen.width < 509) {
    	$('th:nth-child(1)').hide();
        $('td:nth-child(1)').hide();
        $('.card').attr('style', 'padding:0px !important;');
    }
})
</script>
<script>
$( window ).resize(function() {
    if (screen.width < 509) {
        $('th:nth-child(1)').hide();
        $('td:nth-child(1)').hide();
        $('.card').attr('style', 'padding:0px !important;');
    }
    else {
        $('th:nth-child(1)').show();
        $('td:nth-child(1)').show();
        $('.card').removeAttr('style');
    }
    if(screen.width < 509) {
    	$('#hide').hide();
    }
    else {
    	$('#hide').show();
    }
    if(screen.width < 761) {
    	$('table').addClass('table-bordered');
    	$('#details_pc').addClass('d-none');
    	$('#details_mob').removeClass('d-none');

    }
    else {
    	$('table').removeClass('table-bordered');	
    	$('#details_pc').removeClass('d-none');
    	$('#details_mob').addClass('d-none');
    }
});
</script>
<script>
$(document).ready(function() {
    $('.trigger').click(function(event) {
        if (event.target.type !== 'checkbox') {
            $(':checkbox', this).trigger('click');
        }
    });
});
</script>
<script>
function toggle(source) {
	if ($('#main_radio').prop('checked') == true) {
		$('.orm-check-input').each(function(){
  			$(this).prop('checked', true);
  			if($('#cmn-toggle-4').prop('checked') == true) {
  				$(this).parent().parent().addClass('selected')
				$(this).parent().parent().siblings().addClass('selected')
  			}
  			else {
  				$(this).parent().parent().addClass('selected_dark')
				$(this).parent().parent().siblings().addClass('selected_dark')
  			}
	  	})
	}
	else {
		$('.orm-check-input').each(function(){
  			$(this).prop('checked', false);
  			if($('#cmn-toggle-4').prop('checked') == true) {
  				$(this).parent().parent().removeClass('selected')
				$(this).parent().parent().siblings().removeClass('selected')
  			}
  			else {
  				$(this).parent().parent().removeClass('selected_dark')
				$(this).parent().parent().siblings().removeClass('selected_dark')
  			}
	  	})
	}
}
</script>
<script type="text/javascript">
	if(window.localStorage.length == 0) {
        localStorage.setItem("checked", 'true');
    }
	var checked = localStorage.getItem('checked');
	if(checked == 'true') {
		$('#cmn-toggle-4').prop('checked', true);
		$('th').each(function() {
    		$(this).css('background-color', 'white')
    	})
    	$('td').each(function() {
			$(this).css('background-color', 'white')
			$(this).css('color', 'black');
		})
	}
	else if(checked == 'false') {
		$('#cmn-toggle-4').prop('checked', false);
		$('th').each(function() {
    		$(this).css('background-color', '#2c3338')
    	})	
    	$('td').each(function() {
    		$(this).css('background-color', '#2c3338')
    		$(this).css('color', 'white');
    	})
	}
	$('#cmn-toggle-4').change(function(){
	    if(this.checked) {
	    	localStorage.setItem("checked", 'true');
	    	$('th').each(function() {
	    		$(this).css('background-color', 'white')
	    	})
	    	$('td').each(function() {
	    		$(this).css('background-color', 'white')
	    		$(this).css('color', 'black');
	    	})
	    	$('.orm-check-input').each(function() {
	    		if($(this).prop('checked') == true) {
	    			$(this).parent().parent().addClass('selected')
					$(this).parent().parent().siblings().addClass('selected')
					$(this).parent().parent().removeClass('selected_dark')
					$(this).parent().parent().siblings().removeClass('selected_dark')
	    		}
	    	})
	    }
	    else {
	    	localStorage.setItem("checked", 'false');
	    	$('th').each(function() {
	    		$(this).css('background-color', '#2c3338')
	    	})
	    	$('td').each(function() {
	    		$(this).css('background-color', '#2c3338')
	    		$(this).css('color', 'white');
	    	})
	    	if($('.orm-check-input').prop('checked') == true) {
	    		$(this).parent().parent().removeClass('selected')
				$(this).parent().parent().siblings().removeClass('selected')
    			$(this).parent().parent().addClass('selected_dark')
				$(this).parent().parent().siblings().addClass('selected_dark')
    		}
	    }
	});
</script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  	<head>
		<title>AMS</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">
		<style type="text/css">
		@media (min-width: 800px) and (max-width: 850px) {
		        .navbar:not(.top-nav-collapse) {
		            background: #1C2331!important;
		        }
		    }
		</style>  
		<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
	</head>
	<body>
	    {% block content %}
	    {% endblock %}
	    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
	    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
	    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
	    {% block script %}
	    {% endblock %}
	    <footer>
	    	<div class="footer">
	    		Powered By <a href="https://www.devxlabs.co" target="_blank">DevX</a>
	    	</div>
	    </footer>
	</body>
</html>

templates/initial.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<link href="{% static 'css/login.css' %}" rel="stylesheet">
<div class="container container-initial">
	<div id="login" class="mx-auto">
		<div class="pb-4">
			<p class="d-inline pr-5 font-big">Date : <span class="date"></span></p>
			<p class="d-inline font-big">Time : <span class="time"></span></p>
		</div>
		<form method="post" id="initial-form">{% csrf_token %}

          	<fieldset class="clearfix">
	            <div class="form-group col-sm-12 col-md-12">
					<label class="white pb-2" for="subject">Subject:</label>
					{% render_field form.teaches class="form-control" %}
				</div>
          	</fieldset>

        </form>

      </div>
	</div>

{% endblock %}
{% block script %}

{{ super }}
<script>
$(function() {
    if (screen.width < 355) {
    	$('th:nth-child(1)').hide();
        $('td:nth-child(1)').hide();
    }
})
</script>
<script>
$( window ).resize(function() {
    if (screen.width < 355) {
        $('th:nth-child(1)').hide();
        $('td:nth-child(1)').hide();
    }
    else {
        $('th:nth-child(1)').show();
        $('td:nth-child(1)').show();
    }
    if(screen.width < 509) {
    	$('#hide').hide();
    }
    else {
    	$('#hide').show();
    }
    if(screen.width < 761) {
    	$('table').addClass('table-bordered');
    	$('#details_pc').addClass('d-none');
    	$('#details_mob').removeClass('d-none');

    }
    else {
    	$('table').removeClass('table-bordered');	
    	$('#details_pc').removeClass('d-none');
    	$('#details_mob').addClass('d-none');
    }
});
</script>
<script>
$(document).ready(function() {
    $('.table tr').click(function(event) {
        if (event.target.type !== 'checkbox') {
            $(':checkbox', this).trigger('click');
        }
    });
});
</script>
<script>
$(function() {
	$('#id_teaches').change(function() {
		$('#initial-form').submit();
	})
})
</script>
{% endblock %}